version: '3.8'

services:
  backend:
    build:
      context: ./carshowrooms
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      
  frontend:
    build:
      context: ./carshowrooms-f
      dockerfile: Dockerfile
    ports:
      - "80:80"